export class Review {
    constructor(
      public id?: number, // Optional, assuming it's auto-generated by the backend
      public locationId?: number,
      public userId?: number, // Optional, depends on if you're tracking users
      public text?: string,
      //public rating?: number, // Assuming you have a rating system
      public date?: Date // Assuming you want to track when the review was posted
    ) {}
  }
  